site_name: Firefox Docs
nav:
  - 'index.md'
  - 'introduction.md'
  - 'theming.md'
  - 'inspector.md'
  - 'console.md'
  - 'debugger.md'
  - 'network.md'
  - 'privacy-and-security.md'
  - 'accessibility.md'
  - 'style-guide.md'
  - 'back-matter.md'


theme:
  name: readthedocs
