site_name: Firefox Docs
nav:
  - 'index.md'
  - 'inspector.md'
  - 'debugger.md'
  - 'network.md'
  - 'privacy-and-security.md'
  - 'accessibility.md'
  - 'style-guide.md'

theme:
  name: readthedocs
